name: "adapter-pr"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - master


jobs:
  adapter-publish:
    runs-on: prod
    env:
      DOCKER_BUILDKIT: 1
      GHCR_REG: 'ghcr.io/artificialinc'
      DOCKER_REG: 'artificialinc'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          buildkitd-flags: --debug

      # TEMP fix https://github.com/docker/buildx/issues/80, does not affect GHCR
      - name: Config Docker Buildx certs
        run: |
         BUILDER=$(sudo docker ps | grep ${{ steps.buildx.outputs.name }} | cut -f1 -d' ')
         echo builder: $BUILDER
         sudo docker cp /etc/docker/certs.d/ci.reg.notartificial.xyz/ca.crt $BUILDER:/etc/ssl/certs/ci.reg.notartificial.xyz.pem
         sudo docker exec $BUILDER update-ca-certificates
         sudo docker restart $BUILDER

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          logout: false

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: false

      - name: Buildx Image (build + push)
        uses: docker/build-push-action@v2
        id: build_push_image
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            builduser=artificial-build
            buildtoken=${{ secrets.GHCR_TOKEN }}
